version: "3"

services:
  nginx:
    #! Nginx Reverse proxy
    image: nginx
    container_name: cryptoguess-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/ssl/certs:ro
      - ./nginx/certs:/etc/ssl/private:ro
      - ./nginx/error-pages:/etc/nginx/snippets
      # TODO: Link static webpage or create a service for it
    ports:
      - "80:80"
      - "443:443"

  api:
    #! Golang API
    container_name: cryptoguess-api
    build:
      context: ./backend
      dockerfile: ./dockerfile
    expose:
      - "8000"
    depends_on:
      - "nginx"
    environment:
      - GIN_MODE=release
    restart: always

  redis:
    #! Redis database for storage
    container_name: cryptoguess-redis
    restart: always
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

